services:
  trading-journal:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: trading-journal

    restart: unless-stopped

    ports:
      - "8000:8000"

    volumes:
      - ./data:/app/data
      - ./static/uploads:/app/static/uploads
